# <Step1. 탐색> : 데이터의 기초 정보 살펴보기

### [Chipotle 데이터셋의 기본 정보]

In [1]:
# -*- coding: utf-8 -*-

import pandas as pd

# read_csv 함수로 데이터를 Dataframe 형태로 불러옵니다.
file_path = '../data11/chipotle.tsv'
chipo = pd.read_csv(file_path, sep = '\t')

In [2]:
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25
10,5,1,Chips and Guacamole,NaN,$4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25
14,7,1,Chips and Guacamole,NaN,$4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49
18,9,2,Canned Soda,[Sprite],$2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75
20,10,1,Chips and Guacamole,NaN,$4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98
24,12,1,Izze,[Grapefruit],$3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49
...,...,...,...,...,...
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",$11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",$11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",$11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",$8.75
4596,1826,1,Chips and Guacamole,NaN,$4.45
4597,1826,1,Canned Soft Drink,[Nestea],$1.25
4598,1826,1,Bottled Water,NaN,$1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75
4600,1827,1,Chips and Guacamole,NaN,$4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],$1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],$9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$8.75
4605,1828,1,Chips and Guacamole,NaN,$4.45
4606,1828,1,Canned Soft Drink,[Coke],$1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",$11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.25
4609,1829,1,Canned Soft Drink,[Sprite],$1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",$11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$9.25
4613,1831,1,Chips,NaN,$2.15
4614,1831,1,Bottled Water,NaN,$1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",$8.75
4616,1832,1,Chips and Guacamole,NaN,$4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [3]:
print(chipo.shape)
print("------------------------------------")
print(chipo.info())

(4622, 5)
------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null int64
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(2), object(3)
memory usage: 180.6+ KB
None

-----

### [Chipotle 데이터셋의 행과 열, 데이터]

In [4]:
# chipo 라는 Dataframe에서 순서대로 10개의 row 데이터를 보여줍니다.
chipo.head(10)

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98
6,3,1,Side of Chips,NaN,$1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25

In [5]:
print(chipo.columns)
print("------------------------------------")
print(chipo.index)

Index(['order_id', 'quantity', 'item_name', 'choice_description',
       'item_price'],
      dtype='object')
------------------------------------
RangeIndex(start=0, stop=4622, step=1)

-----

##### 이제 데이터의 수치적 특징 탐색을 위한 간단한 질문들을 정의합니다.

- quantity와 item_price의 요약 통계
- order_id와 item_name의 개수

### [Chipotle 데이터셋의 수치적 특징 파악]

##### describe 함수로 요약 통계량 출력하기

In [6]:
chipo['order_id'] = chipo['order_id'].astype(str) # order_id는 숫자의 의미를 가지지 않기 때문에 str으로 변환합니다.

In [7]:
print(chipo.describe()) # chipo dataframe에서 수치형 피처들의 요약 통계량을 확인합니다.

          quantity
count  4622.000000
mean      1.075725
std       0.410186
min       1.000000
25%       1.000000
50%       1.000000
75%       1.000000
max      15.000000

-----

##### unique 함수로 범주형 피처의 개수 출력하기

In [8]:
print(len(chipo['order_id'].unique())) # order_id의 개수를 출력합니다.
print(len(chipo['item_name'].unique())) # item_name의 개수를 출력합니다.

1834
50

-----

# <Step2. 인사이트의 발견> : 탐색과 시각화

-----
##### 다음으로, 인사이트를 발견할 수 있을만한 개념적 질문들을 정의합니다.

- 가장 많이 주문한 item은 무엇인지
- item당 주문의 총량은 얼마인지

In [9]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

from matplotlib import font_manager, rc
plt.rcParams['axes.unicode_minus'] = False

f_path = "/Users/administrator/Library/Fonts/AppleGothic.ttf"
#f_path = "C:/Windows/Fonts/malgun.ttf"
font_name = font_manager.FontProperties(fname=f_path).get_name()
rc('font', family=font_name)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/administrator/Library/Fonts/AppleGothic.ttf'

### [가장 많이 주문한 item]

In [ ]:
item_count = chipo['item_name'].value_counts()[:10] #item_name을 index로 가지는 Series임.
item_count

In [ ]:
type(item_count)

In [ ]:
item_count.index

In [ ]:
item_count.values

In [ ]:
plt.figure(figsize=(18,8))
plt.bar(item_count.index, item_count.values)

In [ ]:
for x in range(len(item_count)):
    print("TOP", x+1 , ":", item_count.index[x], item_count.values[x])

In [ ]:
# 가장 많이 주문한 item : top 10을 출력합니다.
# item_count = chipo['item_name'].value_counts()[:10]
# for idx, (val, cnt) in enumerate(item_count.iteritems(), 1):
#     print("Top", idx, ":", val, cnt)

In [ ]:
#1등은?
chipo['item_name'].value_counts().index.tolist()[0]

-----

### [item당 주문 개수와 총량 구하기]

In [ ]:
# item당 주문 개수를 출력합니다.
order_count = chipo.groupby('item_name')['order_id'].count()
order_count[:10] # item당 주문 개수를 출력합니다.

In [ ]:
# item당 주문 총량을 출력합니다.
item_quantity = chipo.groupby('item_name')['quantity'].sum()
item_quantity[:10] # item당 주문 총량을 출력합니다.

-----

### [시각화로 분석 결과 살펴보기]
- 지금까지의 분석 결과를 간단한 시각화로 표현

In [ ]:
#음식 종류를 알아보자
item_quantity.index.unique()

In [ ]:
#음식 종류 개수를 알아보자
len(item_quantity.index.unique())

In [ ]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

item_name_list = item_quantity.index.tolist()
x_pos = np.arange(len(item_name_list)) #각 항목당 번호를 차례로 붙여보자, 전체 음식종류가 50가지 이므로, 0~49까지 부여
order_cnt = item_quantity.values.tolist()
 
plt.bar(x_pos, order_cnt)
plt.ylabel('ordered_item_count')
plt.title('Distribution of all orderd item')
 
plt.show()

-----

### `[미니 퀴즈 - 1.1]`
- `pandas에서 유용하게 사용되는 함수 value_counts()와 unique()의 차이점은 무엇일까요?` 
    - 각 함수는 어떤 데이터 타입에 적용이 되는지, 어떤 기능을 가지고 있는지, 정확히 어떤 결과값을 반환하는지 실행해봅시다.

In [ ]:
print(chipo['item_name'].value_counts()[:10])

In [ ]:
print(type(chipo['item_name'].value_counts()))

In [ ]:
print(chipo['item_name'].unique()[:10])

In [ ]:
print(type(chipo['item_name'].unique()))

-----

# <Step3. 데이터 전처리> : 나만의 조력자를 정의하자

### [apply와 lambda 함수를 이용한 데이터 전처리]

In [33]:
print(chipo.info())
print('-------------')
chipo['item_price'].head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
order_id              4622 non-null object
quantity              4622 non-null int64
item_name             4622 non-null object
choice_description    3376 non-null object
item_price            4622 non-null object
dtypes: int64(1), object(4)
memory usage: 180.6+ KB
None
-------------

0     $2.39
1     $3.39
2     $3.39
3     $2.39
4    $16.98
Name: item_price, dtype: object

In [34]:
chipo['item_price']

0        $2.39
1        $3.39
2        $3.39
3        $2.39
4       $16.98
5       $10.98
6        $1.69
7       $11.75
8        $9.25
9        $9.25
10       $4.45
11       $8.75
12       $8.75
13      $11.25
14       $4.45
15       $2.39
16       $8.49
17       $8.49
18       $2.18
19       $8.75
20       $4.45
21       $8.99
22       $3.39
23      $10.98
24       $3.39
25       $2.39
26       $8.49
27       $8.99
28       $1.09
29       $8.49
         ...
4592    $11.75
4593    $11.75
4594    $11.75
4595     $8.75
4596     $4.45
4597     $1.25
4598     $1.50
4599     $8.75
4600     $4.45
4601     $1.25
4602     $9.25
4603     $9.25
4604     $8.75
4605     $4.45
4606     $1.25
4607    $11.75
4608    $11.25
4609     $1.25
4610    $11.75
4611    $11.25
4612     $9.25
4613     $2.15
4614     $1.50
4615     $8.75
4616     $4.45
4617    $11.75
4618    $11.75
4619    $11.25
4620     $8.75
4621     $8.75
Name: item_price, Length: 4622, dtype: object

In [35]:
#item_price에서 $를 제거해야함.
result = []
for x in chipo['item_price']:
    result.append(float(x[1:]))
                  
result

[2.39,
 3.39,
 3.39,
 2.39,
 16.98,
 10.98,
 1.69,
 11.75,
 9.25,
 9.25,
 4.45,
 8.75,
 8.75,
 11.25,
 4.45,
 2.39,
 8.49,
 8.49,
 2.18,
 8.75,
 4.45,
 8.99,
 3.39,
 10.98,
 3.39,
 2.39,
 8.49,
 8.99,
 1.09,
 8.49,
 2.39,
 8.99,
 1.69,
 8.99,
 1.09,
 8.75,
 8.75,
 4.45,
 2.95,
 11.75,
 2.15,
 4.45,
 11.25,
 11.75,
 8.75,
 10.98,
 8.99,
 3.39,
 8.99,
 3.99,
 8.99,
 2.18,
 10.98,
 1.09,
 8.99,
 2.39,
 9.25,
 11.25,
 11.75,
 2.15,
 4.45,
 9.25,
 11.25,
 8.75,
 8.99,
 8.99,
 3.39,
 8.99,
 10.98,
 8.99,
 1.69,
 8.99,
 3.99,
 8.75,
 4.45,
 8.75,
 8.75,
 2.15,
 8.75,
 11.25,
 2.15,
 9.25,
 8.75,
 8.75,
 9.25,
 8.49,
 8.99,
 1.09,
 9.25,
 2.95,
 11.75,
 11.75,
 9.25,
 11.75,
 4.45,
 9.25,
 4.45,
 11.75,
 8.75,
 8.75,
 4.45,
 8.99,
 8.99,
 3.99,
 8.49,
 3.39,
 8.99,
 1.09,
 9.25,
 4.45,
 8.75,
 2.95,
 4.45,
 2.39,
 8.49,
 8.99,
 8.49,
 1.09,
 8.99,
 3.99,
 8.75,
 9.25,
 4.45,
 11.25,
 4.45,
 8.99,
 1.09,
 9.25,
 2.95,
 4.45,
 11.75,
 4.45,
 8.49,
 2.39,
 10.98,
 22.5,
 11.75,
 4.45,
 11.25,
 4.45,
 11.25,
 4.45,
 11.25,
 11.25,
 11.75,
 9.25,
 4.45,
 11.48,
 17.98,
 1.69,
 17.5,
 4.45,
 8.49,
 2.39,
 17.5,
 4.45,
 4.45,
 11.25,
 11.75,
 10.98,
 8.49,
 10.98,
 2.18,
 11.48,
 8.49,
 2.39,
 4.45,
 11.25,
 11.75,
 8.75,
 8.49,
 2.18,
 8.49,
 3.39,
 8.49,
 8.99,
 10.98,
 11.48,
 8.49,
 1.09,
 1.09,
 9.25,
 8.75,
 2.95,
 9.25,
 4.45,
 11.25,
 11.48,
 8.49,
 8.49,
 8.99,
 2.39,
 11.25,
 8.75,
 2.95,
 1.09,
 8.99,
 8.49,
 2.39,
 10.98,
 1.09,
 3.99,
 11.25,
 8.75,
 8.49,
 3.39,
 8.75,
 9.25,
 2.15,
 11.25,
 11.25,
 11.25,
 4.45,
 22.5,
 4.45,
 11.75,
 8.75,
 17.5,
 8.75,
 9.25,
 8.75,
 2.15,
 9.25,
 4.3,
 8.75,
 11.25,
 2.15,
 8.99,
 1.09,
 8.99,
 3.99,
 8.75,
 2.95,
 2.95,
 11.75,
 5.9,
 9.25,
 9.25,
 11.75,
 9.25,
 2.95,
 17.5,
 8.75,
 9.25,
 10.98,
 8.99,
 1.09,
 1.09,
 1.09,
 8.99,
 10.98,
 1.09,
 8.75,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 8.99,
 8.99,
 8.99,
 1.09,
 11.75,
 1.25,
 8.99,
 2.39,
 9.25,
 2.95,
 8.99,
 3.99,
 8.49,
 2.39,
 8.49,
 8.49,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 1.69,
 1.09,
 23.78,
 17.5,
 2.15,
 8.75,
 9.25,
 9.25,
 8.75,
 4.45,
 8.75,
 11.25,
 11.25,
 1.25,
 9.25,
 4.45,
 11.25,
 11.75,
 11.75,
 6.49,
 8.99,
 2.39,
 8.49,
 2.39,
 11.25,
 8.75,
 2.15,
 8.99,
 1.69,
 8.75,
 11.25,
 2.15,
 4.45,
 8.75,
 8.49,
 8.99,
 17.5,
 8.49,
 1.09,
 1.09,
 8.75,
 1.25,
 2.15,
 11.08,
 8.49,
 8.49,
 8.99,
 2.39,
 8.75,
 2.15,
 1.5,
 11.25,
 2.15,
 8.49,
 8.49,
 11.75,
 9.25,
 11.75,
 1.25,
 11.25,
 8.75,
 4.45,
 6.49,
 9.25,
 2.95,
 11.25,
 4.45,
 1.25,
 1.25,
 8.49,
 2.39,
 2.18,
 8.49,
 2.18,
 22.16,
 17.5,
 8.75,
 2.95,
 6.49,
 8.99,
 3.39,
 3.39,
 8.99,
 8.49,
 11.25,
 2.15,
 11.25,
 2.95,
 11.25,
 1.25,
 8.99,
 1.09,
 8.75,
 8.75,
 9.25,
 2.95,
 11.75,
 1.5,
 8.99,
 1.09,
 11.25,
 1.25,
 1.25,
 11.25,
 11.75,
 2.15,
 8.99,
 1.69,
 11.75,
 6.49,
 8.75,
 9.25,
 11.25,
 4.45,
 1.25,
 11.25,
 4.45,
 8.49,
 8.99,
 8.49,
 8.99,
 11.25,
 1.25,
 11.75,
 1.25,
 11.75,
 9.25,
 4.45,
 11.25,
 2.15,
 32.94,
 1.25,
 11.25,
 11.48,
 1.69,
 1.09,
 17.5,
 4.45,
 6.49,
 9.25,
 8.75,
 9.25,
 9.25,
 8.75,
 8.75,
 2.15,
 2.95,
 17.5,
 10.98,
 11.48,
 11.48,
 3.39,
 8.99,
 1.69,
 8.99,
 1.09,
 10.98,
 3.39,
 8.99,
 1.09,
 9.25,
 8.75,
 11.25,
 4.45,
 2.95,
 9.25,
 22.2,
 8.49,
 8.99,
 8.75,
 8.75,
 11.75,
 8.75,
 11.25,
 9.25,
 11.25,
 11.25,
 8.75,
 11.25,
 2.95,
 1.25,
 8.49,
 1.69,
 11.75,
 11.25,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.49,
 3.99,
 11.48,
 1.69,
 1.09,
 11.25,
 1.5,
 10.58,
 1.69,
 9.25,
 11.25,
 8.75,
 9.25,
 11.25,
 11.25,
 8.75,
 11.75,
 8.75,
 8.75,
 8.75,
 2.15,
 11.25,
 11.75,
 2.5,
 4.45,
 9.25,
 4.45,
 11.25,
 8.49,
 3.99,
 9.25,
 9.25,
 11.25,
 9.25,
 11.75,
 11.25,
 1.25,
 23.5,
 1.25,
 8.99,
 8.49,
 7.4,
 7.4,
 8.75,
 1.25,
 4.45,
 8.75,
 2.15,
 8.75,
 4.45,
 7.4,
 7.4,
 7.4,
 8.99,
 3.99,
 8.99,
 1.69,
 8.75,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 2.95,
 8.75,
 18.5,
 8.49,
 3.99,
 2.95,
 9.25,
 9.25,
 3.0,
 1.25,
 8.75,
 9.25,
 4.45,
 8.75,
 11.25,
 4.45,
 10.98,
 22.16,
 4.45,
 8.75,
 9.25,
 6.49,
 9.25,
 11.25,
 8.75,
 9.25,
 2.15,
 9.25,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 9.25,
 1.25,
 1.25,
 8.75,
 8.75,
 9.25,
 4.45,
 11.75,
 11.75,
 11.75,
 9.25,
 9.25,
 16.98,
 2.39,
 3.39,
 3.39,
 9.25,
 11.75,
 11.25,
 2.15,
 8.75,
 9.25,
 4.45,
 10.98,
 11.25,
 9.25,
 22.5,
 9.25,
 2.95,
 1.5,
 11.48,
 8.49,
 1.69,
 8.49,
 8.49,
 8.49,
 6.78,
 11.75,
 4.45,
 8.75,
 4.45,
 11.89,
 9.39,
 8.75,
 2.95,
 1.25,
 9.25,
 8.75,
 23.78,
 8.75,
 9.25,
 2.15,
 2.15,
 1.25,
 8.49,
 3.99,
 10.98,
 1.09,
 8.75,
 4.45,
 8.75,
 11.75,
 2.95,
 4.45,
 9.25,
 8.75,
 8.49,
 3.99,
 22.5,
 11.25,
 1.25,
 8.75,
 8.75,
 18.5,
 6.49,
 8.75,
 8.75,
 4.45,
 8.49,
 3.99,
 8.99,
 1.09,
 8.49,
 2.39,
 11.48,
 1.69,
 2.5,
 9.25,
 1.5,
 17.5,
 2.95,
 8.75,
 4.45,
 11.75,
 8.75,
 8.49,
 1.69,
 8.49,
 3.99,
 8.99,
 8.99,
 3.99,
 8.99,
 11.25,
 4.45,
 1.25,
 3.99,
 10.98,
 7.4,
 3.0,
 7.4,
 4.0,
 8.49,
 3.99,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 2.15,
 11.25,
 4.45,
 3.75,
 11.75,
 8.99,
 2.39,
 8.75,
 4.45,
 1.25,
 8.99,
 8.49,
 2.18,
 8.49,
 2.18,
 1.09,
 8.75,
 2.95,
 1.25,
 1.5,
 11.25,
 9.25,
 2.95,
 1.25,
 8.49,
 3.99,
 11.48,
 3.99,
 8.49,
 11.25,
 1.25,
 8.99,
 1.69,
 11.25,
 1.25,
 6.49,
 8.75,
 9.25,
 8.75,
 2.95,
 8.75,
 11.75,
 8.69,
 8.69,
 2.29,
 3.99,
 8.49,
 8.75,
 8.75,
 1.25,
 11.75,
 11.25,
 11.25,
 11.25,
 1.25,
 9.25,
 11.75,
 6.49,
 3.99,
 8.49,
 11.25,
 2.15,
 11.25,
 11.89,
 8.99,
 1.69,
 8.99,
 8.99,
 3.99,
 8.99,
 9.25,
 9.25,
 2.15,
 7.4,
 7.4,
 8.75,
 8.75,
 9.25,
 4.45,
 11.25,
 1.25,
 11.75,
 11.25,
 1.25,
 3.99,
 8.49,
 8.49,
 8.49,
 8.99,
 8.75,
 2.15,
 1.25,
 8.49,
 1.09,
 1.09,
 8.75,
 2.95,
 1.25,
 9.25,
 1.25,
 2.15,
 11.25,
 1.25,
 4.45,
 8.75,
 2.5,
 8.9,
 8.75,
 8.75,
 8.75,
 11.25,
 11.25,
 10.98,
 3.99,
 10.98,
 3.99,
 1.69,
 8.99,
 9.25,
 8.75,
 8.99,
 1.09,
 9.25,
 2.95,
 8.75,
 9.25,
 3.99,
 8.49,
 8.75,
 8.75,
 22.5,
 10.98,
 3.27,
 3.99,
 8.99,
 1.09,
 11.08,
 8.75,
 4.45,
 11.08,
 3.99,
 8.49,
 4.3,
 9.25,
 8.75,
 11.25,
 11.25,
 9.25,
 8.49,
 8.99,
 8.49,
 8.75,
 2.95,
 4.45,
 9.25,
 2.95,
 9.25,
 8.75,
 11.25,
 4.45,
 16.98,
 8.49,
 2.39,
 11.25,
 3.75,
 9.25,
 4.45,
 9.25,
 9.25,
 4.45,
 8.75,
 9.25,
 8.75,
 9.25,
 9.25,
 9.25,
 11.48,
 8.99,
 22.5,
 11.75,
 11.25,
 1.25,
 8.75,
 2.15,
 1.25,
 11.25,
 8.75,
 1.25,
 11.25,
 1.5,
 11.25,
 11.25,
 9.25,
 6.49,
 8.9,
 8.75,
 4.45,
 11.25,
 1.25,
 17.5,
 9.25,
 8.75,
 11.75,
 3.0,
 8.49,
 8.49,
 10.98,
 8.99,
 3.99,
 8.75,
 4.45,
 8.99,
 1.69,
 11.75,
 8.75,
 11.25,
 4.45,
 11.75,
 1.25,
 11.75,
 2.95,
 8.99,
 8.99,
 2.18,
 17.98,
 8.99,
 8.49,
 1.69,
 11.75,
 11.25,
 2.95,
 3.75,
 9.25,
 11.75,
 8.75,
 2.15,
 1.5,
 8.49,
 8.49,
 3.39,
 8.69,
 3.89,
 8.75,
 4.45,
 8.75,
 11.25,
 2.15,
 8.75,
 8.49,
 1.69,
 8.49,
 8.49,
 1.25,
 8.75,
 11.75,
 11.75,
 8.99,
 1.09,
 8.75,
 4.45,
 8.75,
 2.95,
 8.75,
 2.15,
 3.99,
 8.49,
 8.99,
 3.99,
 8.49,
 1.69,
 1.09,
 8.99,
 1.09,
 9.25,
 8.75,
 8.99,
 2.39,
 1.25,
 1.25,
 11.25,
 11.25,
 9.25,
 9.25,
 11.25,
 1.5,
 3.99,
 8.49,
 11.25,
 9.25,
 11.25,
 17.5,
 8.75,
 8.9,
 8.75,
 8.75,
 8.99,
 2.39,
 11.25,
 9.25,
 2.15,
 11.25,
 1.25,
 11.75,
 1.25,
 11.25,
 11.75,
 1.25,
 11.25,
 11.25,
 8.49,
 10.98,
 8.75,
 1.25,
 8.75,
 ...]

In [36]:
chipo.item_price = result
chipo.item_price

0        2.39
1        3.39
2        3.39
3        2.39
4       16.98
5       10.98
6        1.69
7       11.75
8        9.25
9        9.25
10       4.45
11       8.75
12       8.75
13      11.25
14       4.45
15       2.39
16       8.49
17       8.49
18       2.18
19       8.75
20       4.45
21       8.99
22       3.39
23      10.98
24       3.39
25       2.39
26       8.49
27       8.99
28       1.09
29       8.49
        ...
4592    11.75
4593    11.75
4594    11.75
4595     8.75
4596     4.45
4597     1.25
4598     1.50
4599     8.75
4600     4.45
4601     1.25
4602     9.25
4603     9.25
4604     8.75
4605     4.45
4606     1.25
4607    11.75
4608    11.25
4609     1.25
4610    11.75
4611    11.25
4612     9.25
4613     2.15
4614     1.50
4615     8.75
4616     4.45
4617    11.75
4618    11.75
4619    11.25
4620     8.75
4621     8.75
Name: item_price, Length: 4622, dtype: float64

In [37]:
chipo.describe()

          quantity   item_price
count  4622.000000  4622.000000
mean      1.075725     7.464336
std       0.410186     4.245557
min       1.000000     1.090000
25%       1.000000     3.390000
50%       1.000000     8.750000
75%       1.000000     9.250000
max      15.000000    44.250000

In [ ]:
chipo['item_price'].head() #확인해보자

# ------------------------------------------------------------------


# <Step4. 탐색적 분석> : 스무고개로 분석하는 개념적 탐색

##### 데이터를 이해하기 위한 조금 더 복잡한 질문들로 탐색적 데이터 분석 연습하기

- 주문당 평균 계산금액 출력하기
- 한 주문에 10달러 이상 사용한 주문의 id들 출력하기
- 각 아이템의 가격 구하기
- 가장 비싼 주문에서 item이 몇개 팔렸는지 구하기
- “Veggie Salad Bowl”이 몇 번 주문되었는지 구하기
- “Chicken Bowl”을 2개 이상 주문한 주문 횟수 구하기
-----

# ------------------------------------------------------------------

### 주문당 평균 계산금액 출력하기

In [88]:
chipo.groupby('order_id')['item_price'].mean()

order_id
1        2.890000
10       6.600000
100      5.040000
1000    10.250000
1001     5.040000
1002     5.340000
1003     6.500000
1004    21.960000
1005     4.050000
1006     8.925000
1007     3.923333
1008     4.050000
1009     3.090000
101      6.490000
1010     8.310000
1011     3.250000
1012    11.250000
1013     7.975000
1014     5.040000
1015     6.700000
1016    10.750000
1017    11.250000
1018     6.100000
1019     7.850000
102      4.883333
1020     4.883333
1021     6.375000
1022    10.980000
1023    16.980000
1024    18.500000
          ...
972      8.750000
973      9.380000
974      9.000000
975      7.833333
976      8.166667
977      9.985000
978      5.116667
979      8.316667
98       7.433333
980      6.335000
981     10.500000
982      6.850000
983      7.820000
984      4.983333
985     10.980000
986      8.750000
987     11.500000
988      9.985000
989      5.650000
99       6.700000
990      4.156667
991      6.700000
992      6.600000
993      5.090000
994      6.335000
995      8.316667
996     10.750000
997     22.500000
998      5.440000
999      7.312500
Name: item_price, Length: 1834, dtype: float64

In [89]:
type(chipo.groupby('order_id')['item_price'].mean())

pandas.core.series.Series

In [94]:
pricemean = chipo.groupby('order_id')['item_price'].mean()

In [98]:
pricemean.sort_index()

order_id
1        2.890000
10       6.600000
100      5.040000
1000    10.250000
1001     5.040000
1002     5.340000
1003     6.500000
1004    21.960000
1005     4.050000
1006     8.925000
1007     3.923333
1008     4.050000
1009     3.090000
101      6.490000
1010     8.310000
1011     3.250000
1012    11.250000
1013     7.975000
1014     5.040000
1015     6.700000
1016    10.750000
1017    11.250000
1018     6.100000
1019     7.850000
102      4.883333
1020     4.883333
1021     6.375000
1022    10.980000
1023    16.980000
1024    18.500000
          ...
972      8.750000
973      9.380000
974      9.000000
975      7.833333
976      8.166667
977      9.985000
978      5.116667
979      8.316667
98       7.433333
980      6.335000
981     10.500000
982      6.850000
983      7.820000
984      4.983333
985     10.980000
986      8.750000
987     11.500000
988      9.985000
989      5.650000
99       6.700000
990      4.156667
991      6.700000
992      6.600000
993      5.090000
994      6.335000
995      8.316667
996     10.750000
997     22.500000
998      5.440000
999      7.312500
Name: item_price, Length: 1834, dtype: float64

####  한 주문에 40달러 이상 사용한 주문의 id들 출력하기

In [79]:
result2 = order.sum()[order.sum()['item_price']>=40]

In [97]:
result2.index

Index(['1006', '103', '1051', '1170', '1176', '1182', '1243', '1323', '1341',
       '1360', '1426', '1431', '1443', '1449', '1454', '1483', '1511', '1559',
       '1586', '1601', '1655', '1660', '1764', '1786', '1825', '195', '205',
       '231', '343', '488', '491', '511', '561', '576', '577', '635', '649',
       '688', '691', '708', '737', '759', '791', '806', '818', '823', '848',
       '916', '926', '949', '953', '973', '996'],
      dtype='object', name='order_id')

In [102]:
len(result2.index)

53

### 각 아이템의 가격 구하기

In [85]:
chipo['item_name'].unique()

array(['Chips and Fresh Tomato Salsa', 'Izze', 'Nantucket Nectar',
       'Chips and Tomatillo-Green Chili Salsa', 'Chicken Bowl',
       'Side of Chips', 'Steak Burrito', 'Steak Soft Tacos',
       'Chips and Guacamole', 'Chicken Crispy Tacos',
       'Chicken Soft Tacos', 'Chicken Burrito', 'Canned Soda',
       'Barbacoa Burrito', 'Carnitas Burrito', 'Carnitas Bowl',
       'Bottled Water', 'Chips and Tomatillo Green Chili Salsa',
       'Barbacoa Bowl', 'Chips', 'Chicken Salad Bowl', 'Steak Bowl',
       'Barbacoa Soft Tacos', 'Veggie Burrito', 'Veggie Bowl',
       'Steak Crispy Tacos', 'Chips and Tomatillo Red Chili Salsa',
       'Barbacoa Crispy Tacos', 'Veggie Salad Bowl',
       'Chips and Roasted Chili-Corn Salsa',
       'Chips and Roasted Chili Corn Salsa', 'Carnitas Soft Tacos',
       'Chicken Salad', 'Canned Soft Drink', 'Steak Salad Bowl',
       '6 Pack Soft Drink', 'Chips and Tomatillo-Red Chili Salsa', 'Bowl',
       'Burrito', 'Crispy Tacos', 'Carnitas Crispy Tacos', 'Steak Salad',
       'Chips and Mild Fresh Tomato Salsa', 'Veggie Soft Tacos',
       'Carnitas Salad Bowl', 'Barbacoa Salad Bowl', 'Salad',
       'Veggie Crispy Tacos', 'Veggie Salad', 'Carnitas Salad'],
      dtype=object)

In [100]:
chipo_q1 = chipo[chipo['quantity'] == 1]

In [101]:
chipo_q1

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,2.39
1,1,1,Izze,[Clementine],3.39
2,1,1,Nantucket Nectar,[Apple],3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",10.98
6,3,1,Side of Chips,NaN,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",9.25
10,5,1,Chips and Guacamole,NaN,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",11.25
14,7,1,Chips and Guacamole,NaN,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",8.49
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",8.75
20,10,1,Chips and Guacamole,NaN,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",10.98
24,12,1,Izze,[Grapefruit],3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",8.99
28,14,1,Canned Soda,[Dr. Pepper],1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",8.99
...,...,...,...,...,...
4592,1825,1,Barbacoa Burrito,"[Tomatillo Red Chili Salsa, [Rice, Fajita Vege...",11.75
4593,1825,1,Carnitas Bowl,"[Roasted Chili Corn Salsa, [Rice, Sour Cream, ...",11.75
4594,1825,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Pinto Beans, Sour ...",11.75
4595,1826,1,Chicken Bowl,"[Tomatillo Green Chili Salsa, [Rice, Black Bea...",8.75
4596,1826,1,Chips and Guacamole,NaN,4.45
4597,1826,1,Canned Soft Drink,[Nestea],1.25
4598,1826,1,Bottled Water,NaN,1.50
4599,1827,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",8.75
4600,1827,1,Chips and Guacamole,NaN,4.45
4601,1827,1,Canned Soft Drink,[Diet Coke],1.25
4602,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4603,1827,1,Barbacoa Burrito,[Tomatillo Green Chili Salsa],9.25
4604,1828,1,Chicken Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",8.75
4605,1828,1,Chips and Guacamole,NaN,4.45
4606,1828,1,Canned Soft Drink,[Coke],1.25
4607,1829,1,Steak Burrito,"[Tomatillo Green Chili Salsa, [Rice, Cheese, S...",11.75
4608,1829,1,Veggie Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",11.25
4609,1829,1,Canned Soft Drink,[Sprite],1.25
4610,1830,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4611,1830,1,Veggie Burrito,"[Tomatillo Green Chili Salsa, [Rice, Fajita Ve...",11.25
4612,1831,1,Carnitas Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",9.25
4613,1831,1,Chips,NaN,2.15
4614,1831,1,Bottled Water,NaN,1.50
4615,1832,1,Chicken Soft Tacos,"[Fresh Tomato Salsa, [Rice, Cheese, Sour Cream]]",8.75
4616,1832,1,Chips and Guacamole,NaN,4.45
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",8.75

In [109]:
price_per_item = chipo_q1.groupby('item_name').min()
price_per_item['item_price']

item_name
6 Pack Soft Drink                        6.49
Barbacoa Bowl                            8.69
Barbacoa Burrito                         8.69
Barbacoa Crispy Tacos                    8.99
Barbacoa Salad Bowl                      9.39
Barbacoa Soft Tacos                      8.99
Bottled Water                            1.09
Bowl                                     7.40
Burrito                                  7.40
Canned Soda                              1.09
Canned Soft Drink                        1.25
Carnitas Bowl                            8.99
Carnitas Burrito                         8.69
Carnitas Crispy Tacos                    8.99
Carnitas Salad                           8.99
Carnitas Salad Bowl                      9.39
Carnitas Soft Tacos                      8.99
Chicken Bowl                             8.19
Chicken Burrito                          8.19
Chicken Crispy Tacos                     8.49
Chicken Salad                            8.19
Chicken Salad Bowl                       8.75
Chicken Soft Tacos                       8.49
Chips                                    1.99
Chips and Fresh Tomato Salsa             2.29
Chips and Guacamole                      3.89
Chips and Mild Fresh Tomato Salsa        3.00
Chips and Roasted Chili Corn Salsa       2.95
Chips and Roasted Chili-Corn Salsa       2.39
Chips and Tomatillo Green Chili Salsa    2.95
Chips and Tomatillo Red Chili Salsa      2.95
Chips and Tomatillo-Green Chili Salsa    2.39
Chips and Tomatillo-Red Chili Salsa      2.39
Crispy Tacos                             7.40
Izze                                     3.39
Nantucket Nectar                         3.39
Salad                                    7.40
Side of Chips                            1.69
Steak Bowl                               8.69
Steak Burrito                            8.69
Steak Crispy Tacos                       8.69
Steak Salad                              8.69
Steak Salad Bowl                         9.39
Steak Soft Tacos                         8.99
Veggie Bowl                              8.49
Veggie Burrito                           8.49
Veggie Crispy Tacos                      8.49
Veggie Salad                             8.49
Veggie Salad Bowl                        8.75
Veggie Soft Tacos                        8.49
Name: item_price, dtype: float64

### 가장 비싼 주문에서 item이 몇개 팔렸는지 구하기

In [70]:
order = chipo.groupby('order_id')

In [71]:
order.describe()

         item_price                                                        \
              count       mean       std    min      25%     50%      75%
order_id
1               4.0   2.890000  0.577350   2.39   2.3900   2.890   3.3900
10              2.0   6.600000  3.040559   4.45   5.5250   6.600   7.6750
100             2.0   5.040000  5.586144   1.09   3.0650   5.040   7.0150
1000            2.0  10.250000  1.414214   9.25   9.7500  10.250  10.7500
1001            2.0   5.040000  5.586144   1.09   3.0650   5.040   7.0150
1002            2.0   5.340000  5.161880   1.69   3.5150   5.340   7.1650
1003            2.0   6.500000  7.424621   1.25   3.8750   6.500   9.1250
1004            1.0  21.960000       NaN  21.96  21.9600  21.960  21.9600
1005            3.0   4.050000  4.095119   1.25   1.7000   2.150   5.4500
1006            8.0   8.925000  2.983646   2.15   8.7500   9.000  11.2500
1007            3.0   3.923333  4.398106   1.09   1.3900   1.690   5.3400
1008            3.0   4.050000  4.095119   1.25   1.7000   2.150   5.4500
1009            4.0   3.090000  3.611094   1.09   1.0900   1.390   3.3900
101             2.0   6.490000  3.535534   3.99   5.2400   6.490   7.7400
1010            4.0   8.310000  2.743149   4.78   7.5625   8.490   9.2375
1011            4.0   3.250000  4.000000   1.25   1.2500   1.250   3.2500
1012            2.0  11.250000  0.000000  11.25  11.2500  11.250  11.2500
1013            4.0   7.975000  4.075435   4.45   4.4500   7.850  11.3750
1014            2.0   5.040000  5.586144   1.09   3.0650   5.040   7.0150
1015            2.0   6.700000  6.434672   2.15   4.4250   6.700   8.9750
1016            3.0  10.750000  1.322876   9.25  10.2500  11.250  11.5000
1017            2.0  11.250000  0.000000  11.25  11.2500  11.250  11.2500
1018            2.0   6.100000  4.454773   2.95   4.5250   6.100   7.6750
1019            2.0   7.850000  4.808326   4.45   6.1500   7.850   9.5500
102             3.0   4.883333  3.348632   2.95   2.9500   2.950   5.8500
1020            3.0   4.883333  3.348632   2.95   2.9500   2.950   5.8500
1021            2.0   6.375000  6.894291   1.50   3.9375   6.375   8.8125
1022            1.0  10.980000       NaN  10.98  10.9800  10.980  10.9800
1023            1.0  16.980000       NaN  16.98  16.9800  16.980  16.9800
1024            1.0  18.500000       NaN  18.50  18.5000  18.500  18.5000
...             ...        ...       ...    ...      ...     ...      ...
972             3.0   8.750000  0.000000   8.75   8.7500   8.750   8.7500
973             5.0   9.380000  1.065129   8.75   8.7500   8.900   9.2500
974             2.0   9.000000  0.353553   8.75   8.8750   9.000   9.1250
975             3.0   7.833333  4.446441   3.00   5.8750   8.750  10.2500
976             3.0   8.166667  5.778913   1.50   6.3750  11.250  11.5000
977             2.0   9.985000  1.407142   8.99   9.4875   9.985  10.4825
978             3.0   5.116667  3.350124   2.15   3.3000   4.450   6.6000
979             3.0   8.316667  3.494758   4.45   6.8500   9.250  10.2500
98              3.0   7.433333  2.725038   4.30   6.5250   8.750   9.0000
980             2.0   6.335000  6.569022   1.69   4.0125   6.335   8.6575
981             2.0  10.500000  1.767767   9.25   9.8750  10.500  11.1250
982             2.0   6.850000  3.394113   4.45   5.6500   6.850   8.0500
983             3.0   7.820000  3.542838   3.99   6.2400   8.490   9.7350
984             3.0   4.983333  4.026578   1.25   2.8500   4.450   6.8500
985             1.0  10.980000       NaN  10.98  10.9800  10.980  10.9800
986             2.0   8.750000  0.000000   8.75   8.7500   8.750   8.7500
987             2.0  11.500000  0.353553  11.25  11.3750  11.500  11.6250
988             2.0   9.985000  2.114249   8.49   9.2375   9.985  10.7325
989             3.0   5.650000  5.106858   1.25   2.8500   4.450   7.8500
99              2.0   6.700000  6.434672   2.15   4.4250   6.700   8.9750
990             3.0   4.156667  4.235957   1.09   1.7400   2.390   5.6900
991             2.0   6.700000  6.434672   2.15   4.4250   6.700   8.9750
992             2.0   6.600000  3.040559   4.45   5.5250   6.600   7.6750
993             2.0   5.090000  4.808326   1.69   3.3900   5.090   6.7900
994             2.0   6.335000  6.569022   1.69   4.0125   6.335   8.6575
995             3.0   8.316667  3.494758   4.45   6.8500   9.250  10.2500
996             4.0  10.750000  1.354006   8.75  10.6250  11.250  11.3750
997             1.0  22.500000       NaN  22.50  22.5000  22.500  22.5000
998             2.0   5.440000  4.313351   2.39   3.9150   5.440   6.9650
999             4.0   7.312500  3.216980   2.50   7.1875   8.750   8.8750

                quantity
            max    count      mean       std  min  25%  50%   75%  max
order_id
1          3.39      4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
10         8.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
100        8.99      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1000      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1001       8.99      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1002       8.99      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1003      11.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1004      21.96      1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
1005       8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1006      11.25      8.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1007       8.99      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1008       8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1009       8.49      4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
101        8.99      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1010      11.48      4.0  1.250000  0.500000  1.0  1.0  1.0  1.25  2.0
1011       9.25      4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1012      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1013      11.75      4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1014       8.99      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1015      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1016      11.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1017      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1018       9.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1019      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
102        8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1020       8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1021      11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
1022      10.98      1.0  1.000000       NaN  1.0  1.0  1.0  1.00  1.0
1023      16.98      1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
1024      18.50      1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
...         ...      ...       ...       ...  ...  ...  ...   ...  ...
972        8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
973       11.25      5.0  1.200000  0.447214  1.0  1.0  1.0  1.00  2.0
974        9.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
975       11.75      3.0  1.333333  0.577350  1.0  1.0  1.0  1.50  2.0
976       11.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
977       10.98      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
978        8.75      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
979       11.25      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
98         9.25      3.0  1.333333  0.577350  1.0  1.0  1.0  1.50  2.0
980       10.98      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
981       11.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
982        9.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
983       10.98      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
984        9.25      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
985       10.98      1.0  1.000000       NaN  1.0  1.0  1.0  1.00  1.0
986        8.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
987       11.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
988       11.48      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
989       11.25      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
99        11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
990        8.99      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
991       11.25      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
992        8.75      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
993        8.49      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
994       10.98      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
995       11.25      3.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
996       11.75      4.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
997       22.50      1.0  2.000000       NaN  2.0  2.0  2.0  2.00  2.0
998        8.49      2.0  1.000000  0.000000  1.0  1.0  1.0  1.00  1.0
999        9.25      4.0  1.250000  0.500000  1.0  1.0  1.0  1.25  2.0

[1834 rows x 16 columns]

In [72]:
order = chipo.groupby('order_id')

In [73]:
order.sum()[order.sum()['item_price'] == 205.25]['quantity']

order_id
926    23
Name: quantity, dtype: int64

 ### Veggie Salad Bowl”이 몇 번 주문되었는지 구하기

In [30]:
result5 = chipo[chipo['item_name']=='Veggie Salad Bowl']
result5.count()

order_id              18
quantity              18
item_name             18
choice_description    18
item_price            18
dtype: int64

### “Chicken Bowl”을 2개 이상 주문한 주문 횟수 구하기

In [17]:
result4 = chipo[chipo['item_name']=='Chicken Bowl']

In [31]:
result4[result4['quantity'] >= 2]['order_id'].count()

33